deploy-blog4:
  stage: deploy
  script:
    - rsync -arv ./blog4 /
    - cd /blog4
    - bundle install
    - rails db:migrate
    - sv restart blog4
  only:
  - blog4

test-project:
  stage: test
  script:
    - cd project
    - bundle install
    - rails db:migrate RAILS_ENV=test
    - PARALLEL_WORKERS=1 rails test
  only:
    - cookbook3

deploy-project:
  stage: deploy
  script:
    - pumactl stop -P /project/tmp/pids/server.pid || true
    - rsync -arv --delete ./project /
    - cd /project
    - bundle install
    - rails db:migrate
    - rails server -d -b 0.0.0.0 -p 5000
  only:
    - project
